site_name: Buggg的小屋

nav:
  - 主页: 
    - 简介: index.md
  - 概率论与数理统计:
    - 简介: 概统/index.md
    - 样本空间 随机事件: 概统/chapter_1.md
    - 事件的相互关系及运算: 概统/chapter_2.md
    - 频率: 概统/chapter_3.md
    - 概率: 概统/chapter_4.md
    - 等可能概型(古典概型): 概统/chapter_5.md
    - 条件概率: 概统/chapter_6.md
    - 全概率公式与贝叶斯公式:
      - 划分: 概统/chapter_7_1.md
      - 全概率公式: 概统/chapter_7_2.md
      - 贝叶斯公式: 概统/chapter_7_3.md
    - 事件独立性: 概统/chapter_8.md
    - 随机变量: 概统/chapter_9.md
    - 离散型随机变量: 概统/chapter_10.md
    - 分布函数: 概统/chapter_11.md
    - 连续型随机变量及其概率密度: 概统/chapter_12.md
    - 均匀分布与指数分布: 概统/chapter_13.md
    - 正态分布: 概统/chapter_14.md
    - 随机变量函数的分布: 概统/chapter_15.md
  - 算法专题报告:
    - 简介: 算法/index.md
    - 自动机入门: 算法/自动机入门.md
    - 最大流入门: 算法/最大流入门.md
  - 中学知识:
    - 简介: 中学/index.md
    - 初中:
      - 物理: 中学/初中/物理.md
    - 高中:
      - 数学:
        - 三角函数: 中学/高中/数学/三角函数.md
      - 政治:
        - 经济常识: 中学/高中/政治/经济常识/经济常识.md
        - 哲学常识: 中学/高中/政治/哲学常识/哲学常识.md
        - 政治常识: 中学/高中/政治/政治常识/政治常识.md
      - 地理:
        - 自然地理: 中学/高中/地理/自然地理/自然地理.md
        - 人文地理: 中学/高中/地理/人文地理/人文地理.md
        - 拓展部分: 中学/高中/地理/拓展部分/拓展部分.md
        - 专题: 中学/高中/地理/专题/专题.md

repo_url: https://github.com/1216105249/wiki

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: 切换亮色模式
    - scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换暗色模式
  features:
    - navigation.tabs
    - search.suggest
    - search.share
  icon:
    repo: fontawesome/brands/github-alt

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'js/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/1216105249
      name: Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:<1216105249@qq.com>
      name: 邮箱

copyright: Copyright &copy; 2022 Buggg的小屋

edit_uri: ""

plugins:
  - git-revision-date-localized:
      type: iso_datetime
  - search